site_name: matchavez.com
theme: 
  name: material
  #name: readthedocs
  #name: mkdocs

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.tabs
    #- navigation.instant

  palette:
    scheme: default
    primary: red 
    accent: red
    scheme: slate
  
  font:
    text: Roboto
    code: Roboto Mono
  #favicon: assets/favicon.png
  #icon:
    #logo: logo

# Page Tree
nav:
  - HOME: index.md 
  - Blank1: 
    - Unit Tests: unit_testing.md 
    - Fonty Fonts: typography.md 
  - Blank2:
    - Touchy shit: testsnip.md 
  - Blank3: 
    - Unit Tests: unit_testing.md 
    - Fonty Fonts: typography.md 
  - Blank4:
    - Another one: testsnip.md


# Extensions
markdown_extensions:
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
