# Here's the Docker Command, no hashtag:
# docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material

site_name: matchavez.com
theme: 
  name: material
  #name: readthedocs
  #name: mkdocs
  features:
    - navigation.tabs

  # Default values, taken from mkdocs_theme.yml
  language: en

    #- navigation.instant

  palette:
    scheme: mycolour
    #primary: yellow 
    #accent: red

  font:
    text: Roboto
    code: Roboto Mono
  #favicon: assets/favicon.png
  #icon:
    #logo: logo

extra_css:
  - stylesheets/extra.css

# Page Tree
nav:
  - Welcome:
    - Sandbox: unit_testing.md 
    - Another one: testsnip.md
    - Fonty Fonts: typography.md 
    - Steps: steps.md 


# Extensions
markdown_extensions:
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

  